### ISSUE TITLE
Unable to load spatial temporal database 

### ISSUE THREAD

**Issue by mhotan** [mhotan/CityBikeDataExplorer#15]
Ok sorry I went a little Merge Pull Request Crazy and pulled some code that did not work properly.  I am attempting to populate the spatial database and it is failing.

Creating the error.  On the Master branch.
- ./gradlew build
- java -jar st-db-driver/build/libs/st-db-driver-execjar-1.0.jar

Error presented to command line
- org.postgresql.util.PSQLException: ERROR: relation "station_index_station_id" already exists

**Comment by coyotebush** [comment]
That error sounds like the code  (added in d724873399975862f85f9d9e6bbcdfded7e9d6cf then fixed in f16ecacfb9ea2e0d59c47a542967b88758d275d4) is attempting to create indexes that already exist. I don't see a `CREATE INDEX IF NOT EXISTS` in Postgres, unfortunately.

Maybe we'll just have to drop the tables first each time?

**Comment by mhotan** [comment]
Yeah I dropped the database and recreated it and it still didn't work.  Im not diving into it but should be a simple fix later.
